version: "3.9"
services:
  bot:
    container_name: udv_qna_bot
    image: ${BOT_IMAGE_NAME:-ghcr.io/mikhailantoshkin/udv-qna-bot}:${BOT_IMAGE_VERSION:-main}
    restart: always
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    volumes:
      - ${DB_DIR:-.database}:/data
      - ${STATIC_DIR:-.static}:/static
    environment:
      DB_PATH: /data/bot.db
      TELOXIDE_TOKEN: ${TELOXIDE_TOKEN}
      USE_AUTH: ${USE_AUTH:-true}
      STATIC_DIR: /static
  server:
    container_name: udv_qna_bot_managment_server
    image: ${SERVER_IMAGE_NAME:-ghcr.io/mikhailantoshkin/udv-qna-cms}:${SERVER_IMAGE_VERSION:-main}
    restart: always
    build:
      context: .
      dockerfile: ./server/Dockerfile
    volumes:
      - ${DB_DIR:-.database}:/data
      - ${STATIC_DIR:-.static}:/static
    environment:
      DB_PATH: /data/bot.db
      STATIC_DIR: /static
    ports:
      - "${SERVER_BIND_PORT:-8080}:3000"
