version: "3.9"
services:
  bot:
    container_name: bot
    image: ${BOT_IMAGE_NAME:-udv-qna-bot}:latest
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    volumes:
      - ${DB_DIR:-./database}:/data
      - ${STATIC_DIR:-./static}:/static
    environment:
       DB_PATH: /data/bot.db
       TELOXIDE_TOKEN: ${TELOXIDE_TOKEN}
       USE_AUTH: ${USE_AUTH:-true}
       STATIC_DIR: /static
  cms:
    container_name: cms
    image: ${CMS_IMAGE_NAME:-udv-qna-cms}:latest
    build:
      context: .
      dockerfile: ./cms/Dockerfile
    volumes_from:
      - bot
    environment:
       DB_PATH: /data/bot.db
       STATIC_DIR: /static
    ports:
      - "${CMS_BIND_PORT:-8080}:8000"