version: "3.9"
services:
  bot:
    container_name: bot
    image: udv-qna-bot:latest
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    volumes:
      - ${DB_PATH:-./database/bot.db}:/data/bot.db
      - ${STATIC_DIR:-./static}:/static
    environment:
       DB_PATH: /data/bot.db
       TELOXIDE_TOKEN: ${TELOXIDE_TOKEN}
       USE_AUTH: ${USE_AUTH:-true}
       STATIC_DIR: /static
  cms:
    container_name: cms
    image: udv-qna-cms:latest
    build:
      context: .
      dockerfile: ./cms/Dockerfile
    volumes:
      - ${DB_PATH:-./database/bot.db}:/data/bot.db
      - ${STATIC_DIR:-./static}:/static
    environment:
       DB_PATH: /data/bot.db
       STATIC_DIR: /static
    ports:
      - "8080:8000"